# Site settings
title: "sadhasivam"
description: "technology leader "

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Sadhasivam Jayabalaganesan"
resume_title:                   "Leadership in customer-driven technological platform"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "sadhasivam@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+1 610-483-7859"
resume_contact_address:         "Chester Springs, PA 19425"

resume_header_contact_info:     "Chester Springs, PA 19425 • sadhasivam@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Fluid technologist specialized in architecting eCommerce technology stacks. Deep-rooted understanding in eCommerce strategies, Payment Gateways, Engineering practices, Startup Culture, Strategic approaches, Cross Culture infrastructure detailing. Passion for Developer Experience, Product Management, and Developer Relations. Love Building Tools. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/sadhasivam"
  resume_linkedin_url:          "https://www.linkedin.com/in/sadhasivam"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
